### ISSUE TITLE
Using on 1D time series

### ISSUE THREAD

**Issue by ericleonardo** [danm0nster/mdembedding#2]
Hi! Is it possible to use the tool on 1 dimension time series? Thanks

**Comment by danm0nster** [comment]
Yes, you can use it for one dimensional time series. Here's a very brief example using `mdDelay()` for a very short time series:
```
x = [1, 2, 1, 2, 1, 2, 1, 2, 3, 1, 2, 3, 4, 1, 2, 3, 4, 5]';
mdDelay(x)
```

This should give you a plot of the mutual information between the time series and lagged versions at different lag values, and return the location of the first local minimum (3):
```
No value below threshold found. Will use first local minimum instead

ans =

     3

```
